export type Campus = "SGW" | "LOY";

export type BuildingRecord = {
  campus: Campus;
  code: string;
  shortName: string;
  longName: string;
  address: string;
  latitude: number;
  longitude: number;
};

export const BUILDINGS: BuildingRecord[] = [
  {
    campus: "LOY",
    code: "AD",
    shortName: "AD Building",
    longName: "Administration Building",
    address: "7141, Sherbrooke West",
    latitude: 45.457984,
    longitude: -73.639834,
  },
  {
    campus: "SGW",
    code: "B",
    shortName: "B Building",
    longName: "B Annex",
    address: "2160 Bishop Street",
    latitude: 45.497856,
    longitude: -73.579588,
  },
  {
    campus: "LOY",
    code: "BB",
    shortName: "BB Building",
    longName: "BB-BH Annex",
    address: "3502 Bermore Avenue",
    latitude: 45.459793,
    longitude: -73.639174,
  },
  {
    campus: "LOY",
    code: "BH",
    shortName: "BH Building",
    longName: "BB-BH Annex",
    address: "3500 Bermore Avenue",
    latitude: 45.459819,
    longitude: -73.639152,
  },
  {
    campus: "LOY",
    code: "CC",
    shortName: "CC Building",
    longName: "Central Building",
    address: "7141 Sherbrooke West",
    latitude: 45.458204,
    longitude: -73.6403,
  },
  {
    campus: "SGW",
    code: "CI",
    shortName: "CI Building",
    longName: "CI Annex",
    address: "2149 Mackay Street",
    latitude: 45.497467,
    longitude: -73.579925,
  },
  {
    campus: "LOY",
    code: "CJA",
    shortName: "CJ Building - wing A",
    longName: "Communication Studies and Journalism Building",
    address: "7141, Sherbrooke Wes",
    latitude: 45.457478,
    longitude: -73.640354,
  },
  {
    campus: "LOY",
    code: "CJN",
    shortName: "CJ Building - wing N",
    longName: "Communication Studies and Journalism Building",
    address: "7141, Sherbrooke Wes",
    latitude: 45.457478,
    longitude: -73.640354,
  },
  {
    campus: "LOY",
    code: "CJS",
    shortName: "CJ Building - wing S",
    longName: "Communication Studies and Journalism Building",
    address: "7141, Sherbrooke Wes",
    latitude: 45.457478,
    longitude: -73.640354,
  },
  {
    campus: "SGW",
    code: "CL",
    shortName: "CL Building",
    longName: "CL Annex",
    address: "1665 Ste-Catherine W",
    latitude: 45.494259,
    longitude: -73.579007,
  },
  {
    campus: "SGW",
    code: "D",
    shortName: "D Building",
    longName: "D Annex",
    address: "2140 Bishop Street",
    latitude: 45.497827,
    longitude: -73.579409,
  },
  {
    campus: "SGW",
    code: "EN",
    shortName: "EN Building",
    longName: "EN Annex",
    address: "2070 Mackay Street",
    latitude: 45.496944,
    longitude: -73.579555,
  },
  {
    campus: "SGW",
    code: "ER",
    shortName: "ER Building",
    longName: "ER Building",
    address: "2155 Guy Street",
    latitude: 45.496428,
    longitude: -73.57999,
  },
  {
    campus: "SGW",
    code: "ES",
    shortName: "ES Building",
    longName: "ES Building",
    address: "2135 Guy Street",
    latitude: 45.496172,
    longitude: -73.579922,
  },
  {
    campus: "SGW",
    code: "ET",
    shortName: "ET Building",
    longName: "ET Building",
    address: "2125-2127 Guy Street",
    latitude: 45.496163,
    longitude: -73.579904,
  },
  {
    campus: "SGW",
    code: "EV",
    shortName: "EV Building",
    longName: "Engineering, Computer Science and Visual Arts Integrated Complex",
    address: "1515 Ste-Catherine W",
    latitude: 45.495376,
    longitude: -73.577997,
  },
  {
    campus: "SGW",
    code: "FA",
    shortName: "FA Building",
    longName: "FA Annex",
    address: "2060 Mackay Street",
    latitude: 45.496874,
    longitude: -73.579468,
  },
  {
    campus: "SGW",
    code: "FB",
    shortName: "FB Building",
    longName: "Faubourg Building",
    address: "1250 Guy Street",
    latitude: 45.494666,
    longitude: -73.577603,
  },
  {
    campus: "LOY",
    code: "FC",
    shortName: "FC Building",
    longName: "F.C. Smith Building",
    address: "7141 Sherbrooke West",
    latitude: 45.458493,
    longitude: -73.639287,
  },
  {
    campus: "SGW",
    code: "FG",
    shortName: "FG Building",
    longName: "Faubourg Ste-Catherine Building",
    address: "1610 Ste-Catherine",
    latitude: 45.494381,
    longitude: -73.578425,
  },
  {
    campus: "SGW",
    code: "GA",
    shortName: "GA Building",
    longName: "Grey Nuns Annex",
    address: "1211-1215 St-Mathieu",
    latitude: 45.494123,
    longitude: -73.57787,
  },
  {
    campus: "LOY",
    code: "GE",
    shortName: "GE Building",
    longName: "Centre for Structural and Functional Genomics",
    address: "7141 Sherbrooke W",
    latitude: 45.457017,
    longitude: -73.640432,
  },
  {
    campus: "SGW",
    code: "GM",
    shortName: "GM Building",
    longName: "Guy-De Maisonneuve Building",
    address: "1550 DeMaisonneuve W",
    latitude: 45.495983,
    longitude: -73.578824,
  },
  {
    campus: "SGW",
    code: "GNA",
    shortName: "GN Building - wing A",
    longName: "Grey Nuns Building",
    address: "1190 Guy Street",
    latitude: 45.493622,
    longitude: -73.577003,
  },
  {
    campus: "SGW",
    code: "GNB",
    shortName: "GN Building - wings B, C, D, E, F, G, P",
    longName: "Grey Nuns Building",
    address: "1190 Guy Street",
    latitude: 45.493622,
    longitude: -73.577003,
  },
  {
    campus: "SGW",
    code: "GNH",
    shortName: "GN Building - wings H, I, J, K",
    longName: "Grey Nuns Building",
    address: "1190 Guy Street",
    latitude: 45.493622,
    longitude: -73.577003,
  },
  {
    campus: "SGW",
    code: "GNL",
    shortName: "GN Building - wings L, M, N",
    longName: "Grey Nuns Building",
    address: "1190 Guy Street",
    latitude: 45.493622,
    longitude: -73.577003,
  },
  {
    campus: "SGW",
    code: "GS",
    shortName: "GS Building",
    longName: "Guy-Sherbrooke Building",
    address: "1538, Sherbrooke W",
    latitude: 45.496673,
    longitude: -73.581409,
  },
  {
    campus: "SGW",
    code: "H",
    shortName: "H Building",
    longName: "Henry F. Hall Building",
    address: "1455 DeMaisonneuve W",
    latitude: 45.497092,
    longitude: -73.5788,
  },
  {
    campus: "LOY",
    code: "HA",
    shortName: "HA Building",
    longName: "Hingston Hall, wing HA",
    address: "7141 Sherbrooke West",
    latitude: 45.459356,
    longitude: -73.64127,
  },
  {
    campus: "LOY",
    code: "HB",
    shortName: "HB Building",
    longName: "Hingston Hall, wing HB",
    address: "7141 Sherbrooke West",
    latitude: 45.459308,
    longitude: -73.641849,
  },
  {
    campus: "LOY",
    code: "HC",
    shortName: "HC Building",
    longName: "Hingston Hall, wing HC",
    address: "7141 Sherbrooke West",
    latitude: 45.459663,
    longitude: -73.64208,
  },
  {
    campus: "LOY",
    code: "HU",
    shortName: "HU Building",
    longName: "Applied Science Hub",
    address: "7141, Sherbrooke W",
    latitude: 45.458513,
    longitude: -73.641921,
  },
  {
    campus: "LOY",
    code: "JR",
    shortName: "JR Building",
    longName: "Jesuit Residence",
    address: "7141 Sherbrooke West",
    latitude: 45.458432,
    longitude: -73.643235,
  },
  {
    campus: "SGW",
    code: "K",
    shortName: "K Building",
    longName: "K Annex",
    address: "2150 Bishop Street",
    latitude: 45.497777,
    longitude: -73.579531,
  },
  {
    campus: "SGW",
    code: "LB",
    shortName: "LB Building",
    longName: "J.W. McConnell Building",
    address: "1400 DeMaisonneuve W",
    latitude: 45.49705,
    longitude: -73.578009,
  },
  {
    campus: "SGW",
    code: "LC",
    shortName: "LC Building",
    longName: "LC Building",
    address: "1426 Bishop Street",
    latitude: 45.496782,
    longitude: -73.577358,
  },
  {
    campus: "SGW",
    code: "LD",
    shortName: "LD Building",
    longName: "LD Building",
    address: "1424 Bishop Street",
    latitude: 45.496697,
    longitude: -73.577312,
  },
  {
    campus: "SGW",
    code: "M",
    shortName: "M Building",
    longName: "M Annex",
    address: "2135 Mackay Street",
    latitude: 45.497368,
    longitude: -73.579777,
  },
  {
    campus: "SGW",
    code: "MB",
    shortName: "MB Building",
    longName: "John Molson Building",
    address: "1450 Guy Street",
    latitude: 45.495304,
    longitude: -73.579044,
  },
  {
    campus: "SGW",
    code: "MI",
    shortName: "MI Building",
    longName: "MI Annex",
    address: "2130 Bishop Street",
    latitude: 45.497807,
    longitude: -73.579261,
  },
  {
    campus: "SGW",
    code: "MK",
    shortName: "MK Building",
    longName: "MK Annex",
    address: "2000-20002 Mackay St",
    latitude: 45.496606,
    longitude: -73.579025,
  },
  {
    campus: "SGW",
    code: "MM",
    shortName: "MM Building",
    longName: "MM Annex",
    address: "1209 Guy Street",
    latitude: 45.494665,
    longitude: -73.576365,
  },
  {
    campus: "SGW",
    code: "MN",
    shortName: "MN Building",
    longName: "MN Annex",
    address: "1205-1207 Guy Street",
    latitude: 45.494568,
    longitude: -73.576315,
  },
  {
    campus: "SGW",
    code: "MT",
    shortName: "MT Building",
    longName: "Montefiore Building",
    address: "1195 Guy Street",
    latitude: 45.494442,
    longitude: -73.576108,
  },
  {
    campus: "SGW",
    code: "MU",
    shortName: "MU Building",
    longName: "MU Annex",
    address: "2170 Bishop Street",
    latitude: 45.497963,
    longitude: -73.579506,
  },
  {
    campus: "SGW",
    code: "P",
    shortName: "P Building",
    longName: "P Annex",
    address: "2020 Mackay Street",
    latitude: 45.496745,
    longitude: -73.579113,
  },
  {
    campus: "LOY",
    code: "PB",
    shortName: "PB Building",
    longName: "PB Building",
    address: "7200 Sherbrooke W",
    latitude: 45.456534,
    longitude: -73.638106,
  },
  {
    campus: "LOY",
    code: "PC",
    shortName: "PC Building",
    longName: "PERFORM centre",
    address: "7200 Sherbrooke W",
    latitude: 45.457088,
    longitude: -73.637683,
  },
  {
    campus: "SGW",
    code: "PR",
    shortName: "PR Building",
    longName: "PR Annex",
    address: "2100 Mackay Street",
    latitude: 45.497066,
    longitude: -73.57979,
  },
  {
    campus: "LOY",
    code: "PS",
    shortName: "PS Building",
    longName: "Physical Services Building",
    address: "7141 Sherbrooke W",
    latitude: 45.459636,
    longitude: -73.639758,
  },
  {
    campus: "LOY",
    code: "PT",
    shortName: "PT Building",
    longName: "Oscar Peterson Concert Hall",
    address: "7141 Sherbrooke W",
    latitude: 45.459308,
    longitude: -73.638941,
  },
  {
    campus: "LOY",
    code: "PY",
    shortName: "PY Building",
    longName: "Psychology Building",
    address: "7141 Sherbrooke W",
    latitude: 45.458938,
    longitude: -73.640467,
  },
  {
    campus: "SGW",
    code: "Q",
    shortName: "Q Building",
    longName: "Q Annex",
    address: "2010 Mackay Street",
    latitude: 45.496648,
    longitude: -73.579094,
  },
  {
    campus: "SGW",
    code: "R",
    shortName: "R Building",
    longName: "R Annex",
    address: "2050 Mackay Street",
    latitude: 45.496826,
    longitude: -73.579389,
  },
  {
    campus: "LOY",
    code: "RA",
    shortName: "RA Building",
    longName: "Recreation and Athletics Complex",
    address: "7200 Sherbrooke W",
    latitude: 45.456774,
    longitude: -73.63761,
  },
  {
    campus: "LOY",
    code: "RF",
    shortName: "RF Building",
    longName: "Loyola Jesuit Hall and Conference Centre",
    address: "7141 Sherbrooke W",
    latitude: 45.458489,
    longitude: -73.641028,
  },
  {
    campus: "SGW",
    code: "RR",
    shortName: "RR Building",
    longName: "RR Annex",
    address: "2040 Mackay Street",
    latitude: 45.496796,
    longitude: -73.579259,
  },
  {
    campus: "SGW",
    code: "S",
    shortName: "S Building",
    longName: "S Annex",
    address: "2145 Mackay Street",
    latitude: 45.497423,
    longitude: -73.579851,
  },
  {
    campus: "SGW",
    code: "SB",
    shortName: "SB Building",
    longName: "Samuel Bronfman Building",
    address: "1590 Doctor Penfield",
    latitude: 45.4966,
    longitude: -73.58609,
  },
  {
    campus: "LOY",
    code: "SC",
    shortName: "SC Building",
    longName: "Student Centre",
    address: "7141 Sherbrooke W",
    latitude: 45.459131,
    longitude: -73.639251,
  },
  {
    campus: "LOY",
    code: "SH",
    shortName: "SH Building",
    longName: "Solar House",
    address: "7141 Sherbrooke W",
    latitude: 45.459298,
    longitude: -73.642478,
  },
  {
    campus: "LOY",
    code: "SP",
    shortName: "SP Building",
    longName: "Richard J. Renaud Science Complex",
    address: "7141 Sherbrooke W",
    latitude: 45.457881,
    longitude: -73.641565,
  },
  {
    campus: "SGW",
    code: "T",
    shortName: "T Building",
    longName: "T Annex",
    address: "2030 Mackay Street",
    latitude: 45.49671,
    longitude: -73.57927,
  },
  {
    campus: "LOY",
    code: "TA",
    shortName: "TA Building",
    longName: "Terrebonne Building",
    address: "7079 Terrebonne",
    latitude: 45.459992,
    longitude: -73.640897,
  },
  {
    campus: "LOY",
    code: "TB",
    shortName: "TB Building",
    longName: "TB Annex",
    address: "7075 Terrebonne",
    latitude: 45.460051,
    longitude: -73.640842,
  },
  {
    campus: "SGW",
    code: "TD",
    shortName: "TD Building",
    longName: "Toronto-Dominion Building",
    address: "1410 Guy Street",
    latitude: 45.495103,
    longitude: -73.578375,
  },
  {
    campus: "SGW",
    code: "TU",
    shortName: "TU Building",
    longName: "TU Tunnel",
    address: "1550 DeMaisonneuve",
    latitude: 45.49648,
    longitude: -73.578918,
  },
  {
    campus: "SGW",
    code: "V",
    shortName: "V Building",
    longName: "V Annex",
    address: "2110 Mackay Street",
    latitude: 45.497101,
    longitude: -73.579907,
  },
  {
    campus: "SGW",
    code: "VA",
    shortName: "VA Building",
    longName: "Visual Arts Building",
    address: "1395 Rene Levesque W",
    latitude: 45.495543,
    longitude: -73.573795,
  },
  {
    campus: "LOY",
    code: "VE",
    shortName: "VE Building",
    longName: "Vanier Extension",
    address: "7141 Sherbrooke W",
    latitude: 45.458822,
    longitude: -73.638573,
  },
  {
    campus: "LOY",
    code: "VL",
    shortName: "VL Building",
    longName: "Vanier Library Building",
    address: "7141 Sherbrooke W",
    latitude: 45.459026,
    longitude: -73.638606,
  },
  {
    campus: "SGW",
    code: "X",
    shortName: "X Building",
    longName: "X Annex",
    address: "2080 Mackay Street",
    latitude: 45.49694,
    longitude: -73.579593,
  },
  {
    campus: "SGW",
    code: "Z",
    shortName: "Z Building",
    longName: "Z Annex",
    address: "2090 Mackay Street",
    latitude: 45.496981,
    longitude: -73.579705,
  },
];
