coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%
ignore:
  - "test/**"
  - "**/*.test.js"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.js"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/utils/nativeMaps.ts"
  - "**/utils/nativeMaps.web.ts"
  - "coverage/**"
  - "node_modules/**"
  - "*.config.js"
  - "*.config.ts"
  - "babel.config.js"
  - "expo-env.d.ts"
  - "sonar-project.properties"
  - "app.json"
  - "tsconfig.json"
  - "package.json"
  - "package-lock.json"
  - ".codecov.yml"
