sonar.projectKey=team-exception-handlers_soen390-project
sonar.organization=team-exception-handlers

sonar.coverage.exclusions=\
**/*.config.js,\
**/*.config.ts,\
**/babel.config.js,\
**/metro.config.js,\
**/jest.config.js,\
**/expo-env.d.ts,\
**/coverage/**,\
**/__tests__/**,\
**/__mocks__/**,\
**/*.test.ts,\
**/*.test.tsx,\
**/*.spec.ts,\
**/*.spec.tsx,\
**/node_modules/**,\
**/assets/**,\
**/constants/**,\
**/types/**,\
**/styles/**,\
**/theme/**

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=soen390-project
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8