import { StyleSheet } from "react-native";

type CreateMapScreenStylesArgs = {
  isWebPlatform: boolean;
  topInset: number;
  bottomInset: number;
  tabBarHeight: number;
};

export type MapScreenStyles = ReturnType<typeof createMapScreenStyles>;

export function createMapScreenStyles({
  isWebPlatform,
  topInset,
  bottomInset,
  tabBarHeight,
}: Readonly<CreateMapScreenStylesArgs>) {
  return StyleSheet.create({
    floorPlanButtonActive: {
      width: 28,
      height: 28,
      backgroundColor: "rgba(35, 140, 81, 0.8)",
      borderRadius: 8,
      borderWidth: 1,
      borderColor: "#238c51",
      justifyContent: "center",
      alignItems: "center",
    },
    floorPlanButtonTextActive: {
      color: "#FFFFFF",
      fontSize: 11,
      fontWeight: "700",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.85)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      width: "90%",
      height: "75%",
      backgroundColor: "white",
      borderRadius: 20,
      overflow: "hidden",
      position: "relative",
    },
    modalCloseButton: {
      position: "absolute",
      top: 16,
      right: 16,
      zIndex: 10,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "#F5F5F6",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOpacity: 0.2,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
    },
    floorPlanImage: {
      width: "100%",
      height: "100%",
    },
    floorPlanModalChipScroll: {
      flexGrow: 0,
      maxHeight: 44,
      marginTop: 48,
      marginHorizontal: 12,
    },
    floorPlanModalChipScrollContent: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingRight: 8,
    },
    floorPlanModalChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: "#E8E8ED",
      borderWidth: 1,
      borderColor: "transparent",
    },
    floorPlanModalChipActive: {
      backgroundColor: "#1668C7",
      borderColor: "#0d4a8c",
    },
    floorPlanModalChipText: {
      fontSize: 13,
      fontWeight: "600",
      color: "#1F1F24",
    },
    floorPlanModalChipTextActive: {
      color: "#FFFFFF",
    },
    floorPlanModalBody: {
      flex: 1,
      width: "100%",
      minHeight: 0,
    },
    floorPlanLegend: {
      flexDirection: "row",
      justifyContent: "space-around",
      alignItems: "center",
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderTopWidth: 1,
      borderTopColor: "#E0E0E0",
      backgroundColor: "#FAFAFA",
    },
    floorPlanLegendItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    floorPlanLegendSwatch: {
      width: 18,
      height: 18,
      borderRadius: 9,
      borderWidth: 1,
      borderColor: "#FFFFFF",
    },
    floorPlanLegendText: {
      fontSize: 13,
      fontWeight: "600",
      color: "#1F1F24",
    },
    roomInput: {
      flex: 1,
      minWidth: 0,
      height: 28,
      backgroundColor: "rgba(255,255,255,0.06)",
      borderRadius: 8,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.15)",
      color: "white",
      paddingHorizontal: 6,
      fontSize: 12,
    },
    roomInputContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 4,
      gap: 4,
    },
    floorPlanButtonDisabled: {
      width: 28,
      height: 28,
      backgroundColor: "rgba(255,255,255,0.03)",
      borderRadius: 8,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.08)",
      justifyContent: "center",
      alignItems: "center",
    },
    floorPlanButtonTextDisabled: {
      color: "rgba(255,255,255,0.3)",
      fontSize: 11,
      fontWeight: "700",
    },
    indoorRouteButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      marginTop: 8,
      marginHorizontal: 0,
      paddingVertical: 8,
      paddingHorizontal: 14,
      backgroundColor: "rgba(35, 140, 81, 0.85)",
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "#1a6b3e",
    },
    indoorRouteButtonText: {
      color: "#FFFFFF",
      fontSize: 13,
      fontWeight: "700",
    },
    container: {
      flex: 1,
    },
    map: {
      flex: 1,
    },
    markerContainer: {
      alignItems: "center",
    },
    markerBadge: {
      minWidth: 30,
      height: 28,
      paddingHorizontal: 8,
      borderRadius: 14,
      backgroundColor: "#A32638",
      borderWidth: 2,
      borderColor: "white",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOpacity: 0.2,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
    },
    markerText: {
      fontSize: 12,
      fontWeight: "700",
      color: "white",
    },
    markerStem: {
      marginTop: -2,
      width: 0,
      height: 0,
      borderLeftWidth: 6,
      borderRightWidth: 6,
      borderTopWidth: 8,
      borderLeftColor: "transparent",
      borderRightColor: "transparent",
      borderTopColor: "#A32638",
    },
    campusMarkerContainer: {
      alignItems: "center",
      justifyContent: "center",
    },
    campusMarkerBadge: {
      minWidth: 38,
      height: 38,
      paddingHorizontal: 10,
      backgroundColor: "#A32638",
      borderWidth: 2,
      borderColor: "white",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOpacity: 0.22,
      shadowRadius: 5,
      shadowOffset: { width: 0, height: 3 },
      elevation: 4,
      borderRadius: 19,
    },
    campusMarkerText: {
      color: "white",
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 0.2,
    },
    webFallback: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 24,
    },
    webFallbackText: {
      color: "#2C2C2C",
      fontSize: 16,
      textAlign: "center",
    },
    permissionBanner: {
      position: "absolute",
      alignSelf: "center",
      backgroundColor: "#ff3700",
      opacity: 0.9,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 20,
      shadowColor: "#000",
      shadowOpacity: 0.2,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
      zIndex: 5,
      maxWidth: "90%",
    },
    permissionText: {
      fontSize: 13,
      fontWeight: "600",
      color: "white",
      textAlign: "center",
    },
    buildingInfo: {
      position: "absolute",
      top: isWebPlatform ? 53 : topInset + 44,
      alignSelf: "center",
      backgroundColor: "rgba(0,0,0,0.7)",
      paddingVertical: isWebPlatform ? 8 : 4,
      paddingHorizontal: isWebPlatform ? 16 : 8,
      borderRadius: isWebPlatform ? 10 : 8,
      zIndex: 1000,
      maxWidth: isWebPlatform ? undefined : "90%",
    },
    buildingInfoText: {
      color: "white",
      fontSize: isWebPlatform ? 14 : 12,
      fontWeight: "700",
      textAlign: "center",
    },
    buildingInfoTitle: {
      color: "#FFA500",
      fontSize: isWebPlatform ? 14 : 12,
      fontWeight: "600",
      marginBottom: 2,
      textAlign: "center",
      opacity: 0.9,
    },
    searchResultsContainer: {
      marginHorizontal: 16,
      marginTop: 8,
      backgroundColor: "rgba(255,255,255,0.98)",
      borderRadius: 12,
      borderWidth: 1,
      borderColor: "rgba(0,0,0,0.08)",
      overflow: "hidden",
    },
    searchResultsHint: {
      fontSize: 12,
      color: "#5D5D66",
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: "#F6F7FA",
      borderBottomWidth: 1,
      borderBottomColor: "#ECECF1",
      fontWeight: "600",
    },
    searchResultItem: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: "#F0F0F0",
    },
    searchResultCode: {
      color: "#A32638",
      fontWeight: "700",
      fontSize: 13,
    },
    searchResultCampusBadge: {
      color: "#5D5D66",
      fontWeight: "400",
      fontSize: 11,
    },
    searchResultName: {
      marginTop: 3,
      color: "#202124",
      fontSize: 13,
      fontWeight: "500",
    },
    searchResultAddress: {
      marginTop: 2,
      color: "#6A6A75",
      fontSize: 12,
    },
    directionsPanel: {
      marginHorizontal: 16,
      marginTop: 8,
      marginBottom: 8,
      padding: 10,
      borderRadius: 14,
      backgroundColor: "rgba(20,20,24,0.82)",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.15)",
    },
    directionFieldRow: {
      flexDirection: "row",
      gap: 8,
      alignItems: "center",
    },
    directionFieldButton: {
      alignSelf: "stretch",
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.28)",
      paddingVertical: 8,
      paddingHorizontal: 10,
      backgroundColor: "rgba(255,255,255,0.08)",
    },
    directionFieldButtonActive: {
      borderColor: "#FFD08A",
      backgroundColor: "rgba(255,208,138,0.2)",
    },
    directionFieldLabel: {
      color: "#FFD08A",
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.4,
      lineHeight: 14,
      minHeight: 14,
    },
    directionFieldValue: {
      color: "white",
      fontSize: 13,
      marginTop: 3,
      fontWeight: "600",
      lineHeight: 18,
      minHeight: 18,
    },
    clearRouteButton: {
      flexShrink: 0,
      paddingHorizontal: 8,
      paddingVertical: 8,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.28)",
      backgroundColor: "rgba(255,255,255,0.08)",
    },
    clearRouteText: {
      color: "white",
      fontSize: 12,
      fontWeight: "700",
    },
    routeStatusText: {
      marginTop: 10,
      color: "#E8E8EC",
      fontSize: 12,
      fontWeight: "600",
    },
    routeStepsPopup: {
      position: "absolute",
      left: 12,
      right: 12,
      bottom: bottomInset + tabBarHeight + 10,
      backgroundColor: "#F5F5F6",
      borderRadius: 28,
      paddingHorizontal: 14,
      paddingTop: 6,
      paddingBottom: 14,
      zIndex: 1100,
      maxHeight: isWebPlatform ? 360 : 300,
      shadowColor: "#000",
      shadowOpacity: 0.16,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 10,
    },
    routeStepsHandle: {
      alignSelf: "center",
      width: 44,
      height: 28,
      alignItems: "center",
      justifyContent: "center",
      marginTop: -2,
      marginBottom: 4,
    },
    routeStepsCloseButton: {
      position: "absolute",
      top: 14,
      right: 12,
      width: 44,
      height: 44,
      borderRadius: 22,
      borderWidth: 2.5,
      borderColor: "#1F1F24",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#F5F5F6",
    },
    routeStepsCollapsedTab: {
      position: "absolute",
      alignSelf: "center",
      bottom: bottomInset + tabBarHeight + 10,
      width: 58,
      height: 32,
      borderRadius: 16,
      backgroundColor: "#F5F5F6",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 1100,
      shadowColor: "#000",
      shadowOpacity: 0.14,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 8,
    },
    routeStepsList: {
      marginTop: 10,
    },
    routeStepsListContent: {
      paddingRight: 54,
      paddingBottom: 8,
    },
    routeStepText: {
      fontSize: 18,
      lineHeight: 24,
      color: "#111111",
      fontWeight: "700",
      marginBottom: 18,
    },
    itineraryCard: {
      backgroundColor: "white",
      borderRadius: 14,
      padding: 12,
      marginBottom: 10,
      borderWidth: 2,
      borderColor: "#E5E5EA",
    },
    itineraryCardActive: {
      borderColor: "#007AFF",
      backgroundColor: "#F0F7FF",
    },
    itineraryTime: {
      fontSize: 16,
      fontWeight: "700",
      color: "#1C1C1E",
      marginBottom: 4,
    },
    itineraryDuration: {
      fontSize: 13,
      color: "#3A3A3C",
      marginBottom: 2,
    },
    itineraryTransfers: {
      fontSize: 12,
      color: "#8E8E93",
      marginBottom: 8,
    },
    itineraryLegsRow: {
      flexDirection: "row",
      gap: 6,
      flexWrap: "wrap",
    },
    legPill: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      fontSize: 12,
      fontWeight: "600",
    },
    legPillWalk: {
      backgroundColor: "#E8F5E9",
      color: "#2E7D32",
    },
    legPillBus: {
      backgroundColor: "#FFF3E0",
      color: "#E65100",
    },
    legPillSubway: {
      backgroundColor: "#E3F2FD",
      color: "#1565C0",
    },
    legPillTram: {
      backgroundColor: "#F3E5F5",
      color: "#6A1B9A",
    },
    legDetailRow: {
      flexDirection: "row",
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: "#F0F0F0",
    },
    legDetailTime: {
      width: 60,
      fontSize: 13,
      fontWeight: "600",
      color: "#1C1C1E",
    },
    legDetailLine: {
      width: 20,
      alignItems: "center",
      marginRight: 8,
    },
    legDetailContent: {
      flex: 1,
      fontSize: 13,
      color: "#3A3A3C",
    },
    timelineContainer: {
      flexDirection: "row",
      marginBottom: 8,
    },
    timelineLeft: {
      width: 60,
      alignItems: "flex-end",
      paddingRight: 12,
    },
    timelineCenter: {
      width: 40,
      alignItems: "center",
      position: "relative",
    },
    timelineIcon: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "white",
      borderWidth: 2,
      zIndex: 2,
    },
    timelineIconWalk: {
      borderColor: "#2E7D32",
      backgroundColor: "#E8F5E9",
    },
    timelineIconTransit: {
      borderColor: "#007AFF",
      backgroundColor: "#E3F2FD",
    },
    timelineLine: {
      position: "absolute",
      width: 3,
      top: 32,
      bottom: -8,
      backgroundColor: "#E5E5EA",
      left: "50%",
      marginLeft: -1.5,
    },
    timelineLineWalk: {
      backgroundColor: "#2E7D32",
    },
    timelineLineTransit: {
      backgroundColor: "#007AFF",
    },
    timelineRight: {
      flex: 1,
      paddingLeft: 8,
    },
    timelineTime: {
      fontSize: 15,
      fontWeight: "700",
      color: "#1C1C1E",
      marginBottom: 4,
    },
    timelineStopName: {
      fontSize: 14,
      fontWeight: "600",
      color: "#1C1C1E",
      marginBottom: 6,
    },
    timelineWalkDetail: {
      fontSize: 13,
      color: "#6A6A75",
      marginBottom: 4,
    },
    timelineRoutePill: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 6,
      marginBottom: 6,
    },
    timelineRoutePillBus: {
      backgroundColor: "#007AFF",
    },
    timelineRoutePillSubway: {
      backgroundColor: "#007AFF",
    },
    timelineRoutePillTram: {
      backgroundColor: "#9C27B0",
    },
    timelineRouteText: {
      fontSize: 13,
      fontWeight: "700",
      color: "white",
      marginLeft: 6,
    },
    timelineHeadsign: {
      fontSize: 13,
      color: "#3A3A3C",
      marginTop: 2,
    },
    sameCampusHint: {
      color: "rgba(255,255,255,0.55)",
      fontSize: 11,
      fontStyle: "italic",
      alignSelf: "center",
      flex: 1,
      marginLeft: 8,
    },
    modeSelectorGrid: {
      marginTop: 10,
      gap: 8,
    },
    modeSelectorRow: {
      flexDirection: "row",
      gap: 8,
      alignItems: "center",
    },
    modePill: {
      flex: 1,
      paddingVertical: 9,
      paddingHorizontal: 10,
      borderRadius: 22,
      borderWidth: 1.5,
      borderColor: "rgba(255,255,255,0.28)",
      backgroundColor: "rgba(255,255,255,0.10)",
      alignItems: "center",
      justifyContent: "center",
    },
    modePillActive: {
      backgroundColor: "#D2E9FF",
      borderColor: "#95C6F3",
    },
    modePillText: {
      color: "white",
      fontSize: 13,
      fontWeight: "700",
    },
    modePillTextActive: {
      color: "#123B5D",
    },
    modePillSpacer: {
      flex: 1,
    },
    modePillGroup: {
      flex: 1,
      flexDirection: "row",
      gap: 8,
    },
    modeActionButton: {
      paddingHorizontal: 16,
      paddingVertical: 9,
      borderRadius: 22,
      backgroundColor: "rgba(255,255,255,0.15)",
      borderWidth: 1.5,
      borderColor: "rgba(255,255,255,0.35)",
      alignItems: "center",
      justifyContent: "center",
    },
    modeActionButtonText: {
      color: "white",
      fontSize: 13,
      fontWeight: "700",
    },
    roomSuggestionsDropdownWrap: {
      marginTop: 8,
      borderRadius: 12,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.18)",
      backgroundColor: "rgba(12,12,18,0.97)",
      shadowColor: "#000",
      shadowOpacity: 0.45,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 14,
    },
    roomSuggestionsDropdown: {
      maxHeight: 176,
      backgroundColor: "transparent",
    },
    roomSuggestionsDropdownContent: {
      paddingBottom: 4,
    },
    roomSuggestionsHeader: {
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: 6,
      borderBottomWidth: 1,
      borderBottomColor: "rgba(255,208,138,0.2)",
      backgroundColor: "rgba(255,255,255,0.04)",
    },
    roomSuggestionsHeaderText: {
      color: "#FFD08A",
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.6,
      textTransform: "uppercase" as const,
    },
    roomSuggestionItem: {
      paddingHorizontal: 14,
      paddingVertical: 12,
      minHeight: 44,
      justifyContent: "center",
      borderBottomWidth: 1,
      borderBottomColor: "rgba(255,255,255,0.08)",
    },
    roomSuggestionItemLast: {
      borderBottomWidth: 0,
    },
    roomSuggestionItemPressed: {
      backgroundColor: "rgba(255,255,255,0.12)",
    },
    roomSuggestionText: {
      color: "rgba(255,255,255,0.9)",
      fontSize: 13,
      fontWeight: "500",
    },
    e2eControls: {
      position: "absolute",
      left: 12,
      bottom: 110,
      gap: 8,
      zIndex: 1100,
    },
    e2eButton: {
      backgroundColor: "rgba(0,0,0,0.72)",
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.25)",
      alignItems: "center",
      justifyContent: "center",
    },
    e2eButtonText: {
      color: "white",
      fontSize: 12,
      fontWeight: "700",
    },
    nextClassButton: {
      position: "absolute",
      right: 16,
      bottom: "11%",
      width: 100,
      height: 48,
      borderRadius: 24,
      backgroundColor: "#912338",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 1200,
      shadowColor: "#000",
      shadowOpacity: 0.25,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
      elevation: 6,
    },
    nextClassButtonText: {
      color: "white",
      fontSize: 11,
      fontWeight: "700",
    },
    poiButton: {
      position: "absolute",
      left: 16,
      bottom: bottomInset + tabBarHeight + 16,
      width: 100,
      height: 48,
      borderRadius: 24,
      backgroundColor: "#1668C7",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 1200,
      shadowColor: "#000",
      shadowOpacity: 0.25,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
      elevation: 6,
    },
    poiButtonText: {
      color: "white",
      fontSize: 11,
      fontWeight: "700",
    },
    poiMarkerBadge: {
      maxWidth: 120,
      height: 28,
      paddingHorizontal: 8,
      borderRadius: 14,
      backgroundColor: "#1668C7",
      borderWidth: 2,
      borderColor: "white",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOpacity: 0.2,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
    },
    poiMarkerText: {
      fontSize: 10,
      fontWeight: "700",
      color: "white",
    },
    poiMarkerStem: {
      marginTop: -2,
      width: 0,
      height: 0,
      borderLeftWidth: 6,
      borderRightWidth: 6,
      borderTopWidth: 8,
      borderLeftColor: "transparent",
      borderRightColor: "transparent",
      borderTopColor: "#1668C7",
    },
    nextClassAlert: {
      position: "absolute",
      top: "27%",
      alignSelf: "center",
      backgroundColor: "rgba(0,0,0,0.85)",
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 12,
      zIndex: 1200,
    },
    nextClassAlertText: {
      color: "white",
      fontSize: 12,
      fontWeight: "600",
    },
  });
}
